#This file is needed for AWS s3
staging:
  bucket: megam
  use_ssl: false
  access_key_id: <%= ENV['MEGAM_AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MEGAM_AWS_SECRET_ID'] %>

production:
  bucket: megam
  use_ssl: false
  access_key_id: <%= ENV['MEGAM_AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MEGAM_AWS_SECRET_ID'] %>


development:
  bucket: megam
  use_ssl: false
  access_key_id: <%= ENV['MEGAM_AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MEGAM_AWS_SECRET_ID'] %>
  #dynamo_db_endpoint: localhost
  #dynamo_db_port: 4567
  #dynamo_db_endpoint: dynamodb.ap-southeast-1.amazonaws.com # Set the regional endpoint

test:
  bucket: megam
  use_ssl: false
  access_key_id: <%= ENV['MEGAM_AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MEGAM_AWS_SECRET_ID'] %>