monitor:
  metric_source: ganglia
  host: ganglia_host
  base_url: http://monitor.megam.co.in/ganglia
  cluster: megampaas

storage:
  type: local
  aws_access_key: AWS_ACCCESS_KEY
  aws_secret_key: AWS_SECRET_KEY
  cross_cloud: cloud_keys
  cloud_tool: cloudrecipes
  server_url: https://s3-ap-southeast-1.amazonaws.com

api:
  host: api.megam.co
  pub_key: megamgateway_pub.crt
  private_key: megamgateway.key

#if db and production are start from begining of the line it assumes as two inner hashes 
#{"db"=>nil, "production"=>{"adapter"=>"sqlite3"}}
#db:
#  production:
#        adapter: sqlite3
#        database: db/cocdb
#        pool: 5
#        timeout: 5000
