#This file is needed for cross clouds
ec2:
  name: Amazon EC2
  Description: Virtual Servers in the cloud
  type: ec2_keys
  value: ec2
  image: aws
    
hp:
  name: hp cloud
  description: HP Public Cloud is a public cloud service from Hewlett-Packard (HP) that offers compute,storage, and platform services that are accessible via the public Internet to developers, independent software vendors (ISVs), SMBs, and enterprises of all sizes (including public sector).  
  type: hp_keys
  value: hp
  image: hp
    
google:
  name: Google cloud Engine
  description: Compute Engine is an infrastructure as a service that lets you run your large-scale computing workloads on Linux virtual machines hosted on Google's infrastructure.
  type: gce_keys
  value: google
  image: gce  
