#This file is needed for market_places
DRBD:
  name: DRBD
  predef_name: 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: 
  db_model:
  dbms: 
  link:
  type: SERVICE
  
Jenkins:
  name: Jenkins
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: http://mirrors.jenkins-ci.org/war/latest/jenkins.war
  db_model:
  dbms: 
  link:
  type: SERVICE
  
SCMManager:
  name: SCMManager
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://s3-ap-southeast-1.amazonaws.com/megampub/0.1/war/scmmanager.war
  db_model:
  dbms: 
  link:
  type: SERVICE
  
Ghost:
  name: Ghost
  predef_name: nodejs 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/ghost.git
  db_model:
  dbms: 
  link:
  type: SERVICE
  
WordPress:
  name: WordPress
  predef_name: wordpress
  no_of_instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:  
  link:  
  type: SERVICE  

Riak:
  name: Riak
  no_of_instances: 1
  db_model: full
  dbms: riak
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
    
PostgreSQL:
  name: PostgreSQL
  no_of_instances: 1
  db_model: full
  dbms: postgresql
  predef_name:
  radios:
  deps_scm:    
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE

Redis:
  name: Redis
  no_of_instances: 1
  db_model: full
  dbms: redis
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html
  type: SERVICE
  
RabbitMQ:
  name: RabbitMQ
  no_of_instances: 1
  db_model: full
  dbms: rabbitmq
  predef_name:
  radios:
  deps_scm:
  link: http://gomegam.com/docs/users/services/index.html 
  type: SERVICE

Op5:
  name: Op5
  no-of-instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:
  predef_name: op5  
  link:   
  type: SERVICE

Zarafa:
  name: Zarafa
  no-of-instances: 1
  radios: scm_sample
  deps_scm:
  db_model:
  dbms:
  predef_name: zarafa 
  link:
  type: SERVICE

Java:
  name: Java
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://s3-ap-southeast-1.amazonaws.com/megampub/0.1/war/orion.war
  db_model:
  dbms:   
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP 
  
Rails:
  name: Rails
  predef_name: rails 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/aryabhata.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  
Play:
  name: Play
  predef_name: play 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/megam_play.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  
Akka:
  name: Akka
  predef_name: akka 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/megam_akka.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP
  
Nodejs:
  name: Nodejs
  predef_name: nodejs 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/ghost.git
  db_model:
  dbms:  
  link: http://gomegam.com/docs/users/apps/index.html
  type: APP