#This file is needed for market_places
DRBD:
  name: DRBD
  predef_name: 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: 
  
Jenkins:
  name: Jenkins
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: 
  
SCM-Manager:
  name: SCM-Manager
  predef_name: java 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://s3-ap-southeast-1.amazonaws.com/megampub/0.1/war/scmmanager.war
  
Ghost:
  name: Ghost
  predef_name: nodejs 
  no_of_instances: 1
  radios: scm_sample
  deps_scm: https://github.com/thomasalrin/ghost.git
  
WordPress:
  name: WordPress
  predef_name: wordpress
  no_of_instances: 1
  radios: scm_sample
  deps_scm:     
