api:
  host: api.megam.co
  scheme: http
  pub_key: megamgateway_pub.crt
  private_key: megamgateway.key

storage:
  type: riak
  server_url: localhost
  cloud_tool_bucket: cloudtools
  cloud_keys_bucket: cloudaccesskeys
  ssh_files_bucket: sshfiles
  #type :s3
  #server_url: https://s3-ap-southeast-1.amazonaws.com

varai:
  host: localhost
  port: 1880

support:
  email: support@megam.co.in
  password: team4megam

auth:
  fb_client_id:
  fb_secret_key:
  github_client_id: dc161ea567cf79adb11f
  github_secret_key: 5b2b9de2f6e3d86116ed0c9f02f645fc70376887
  assembla_client_id:
  assembla_secret_key:
  google_client_id: 747654586796-8aqmg4t037s1v2r1vaf1qmjlk121s4ji.apps.googleusercontent.com
  google_secret_key: vWm0M_Eiyik9EeIhUeLE95bZ

monitor:
  metric_source: ganglia
  host: ganglia_host
  base_url: http://monitor.megam.co.in/ganglia
  cluster: megampaas

tap:
 host: localhost
 port: 7000

gogs:
 host: localhost
 port: 6001

