# /var/lib/megam/nilavu.yml
defaults: &defaults
# Automatically edited during builds
  build: build.date
## locale: default is english
  locale: en
##Logo for header, signup and signin pages
  logo_header: megam_vertice_logo.png
  logo_white: megam_vertice_logo_signup.png
  logo_black: megam_vertice_logo_signin.png
# Enable billing, turn it off for testing.
  billings: off
## Backup cephgw, host, adminuser, admin password.
  backup:
    enable: off
    host: localhost
    username: megdc
    password: megdc
## log_level: default is debug
  log_level: :info
## Name of the nilavu server, welcome email uses this url
  nilavu: https://console.megam.io
## A database backend for nilavu
  riak: localhost
## An api server for nilavu
  api: localhost
## logs is a host that the nilavu will connect to for real time log streaming
  logs: wss://madai.megam.io/logs
# notification section notifies the handlers based on_trigger conditions.
  notification:
    enable: on
    logo: https://s3-ap-southeast-1.amazonaws.com/megampub/images/mailers/megam_vertice.png
    use: mailgun
    mailgun:
      api_key: <%= ENV["NIL_MAILGUN_APIKEY"] %>
      domain: ojamail.megambox.com
    smtp:
      address: smtp.googlemail.com
      port: 587
      domain: megam.io
      email: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
    hipchat:
      api_key: <%= ENV["NIL_HIP_APIKEY"] %>
      room: "Megam"
    infobip:
      username: <%= ENV["NIL_INFOBIP_USERNAME"] %>
      password: <%= ENV["NIL_INFOBIP_PASSWORD"] %>
      api_key: <%= ENV["NIL_INFOBIP_APIKEY"] %>
      application_id: <%= ENV["NIL_INFOBIP_APPLICATION_ID"] %>
      message_id: <%= ENV["NIL_INFOBIP_MESSAGE_ID"] %>

## Specifies the oauth id/key for various social identities
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
