# /var/lib/megam/nilavu.yml
defaults: &defaults
## locale: default is english
  locale: en
## storage backend is a host that the nilavu will connect to
## for getting information about an account (needs to be removed)
## Default: localhost
##
## Acceptable values:
##   - text, e.g. localhost, console.megam.io

  storage: api.megam.io
## Name of the nilavu server
##
## Default: console.megam.io
##
## Acceptable values:
##   - text
  nilavu: console.megam.io
## connect.http.api is a host that the nilavu will connect to
## for API  interaction
## Default: api.megam.io
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io

  http_api: api.megam.io
## http_logs is a host that the nilavu will connect to for real time log streaming
## Default: console.megam.io:7000
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io
  http_logs: localhost:7777/logs
# Enable billing, turn it off for testing.
## Default: on
##
## Acceptable values:
##   - text, e.g. on or off
  billings: off
## Backup storage, host.
  backup:
    enable: on
    host: 192.168.1.248
    username: thomas
    password: team4megam
# http_gitlab is a host that the nilavu will connect to
## for pulling data from private repositories
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io
  http_gitlab: console.megam.io:6001
# notification section notifies the handlers based on_trigger conditions.
## 1. on_error: When an error occurs then notify dev support via an email to support@megam.io and hipchat. A notification
## via email happens if the configuration for [email:] exists.
## 2. on_some_hap: Turn notification on for notifying when some happenings needs to be notified. (welcome, reset password, balance topup, low credits)
## Default:
##
## Acceptable values:
##   - text
  notification:
    on_errors: on
    on_some_hap: on
    email:
      id: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
      hipchat:
        api_key: <%= ENV["NIL_HIP_APIKEY"] %>
        room: "Megam"

## Specifies the oauth id/key for various social identities
##
## Default:
##
## Acceptable values:
##   - one of: facebook, github, google
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
