# /var/lib/megam/nilavu.yml
defaults: &defaults
# Automatically edited during builds
  build: build.date
# Enable billing, turn it off for testing.
  billings: off
## Backup cephgw, host, adminuser, admin password.
  backup:
    enable: off
    host: localhost
    username: megdc
    password: megdc
## locale: default is english
  locale: en
## log_level: default is debug
  log_level: :info
## Name of the nilavu server, welcome email uses this url
  nilavu: https://console.megam.io
## A database backend for nilavu
  riak: localhost
## An api server for nilavu
  api: localhost
## logs is a host that the nilavu will connect to for real time log streaming
  logs: wss://madai.megam.io/logs
# notification section notifies the handlers based on_trigger conditions.
  notification:
    enable: on
    use: mailgun
    mailgun:
      api_key: <%= ENV["NIL_MAILGUN_APIKEY"] %>
      domain: ojamail.megambox.com
    smtp:
      address: smtp.googlemail.com
      port: 587
      domain: megam.io
      email: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
    hipchat:
      api_key: <%= ENV["NIL_HIP_APIKEY"] %>
      room: "Megam"

## Specifies the oauth id/key for various social identities
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
