# /var/lib/megam/nilavu.yml
defaults: &defaults
## locale: default is english
  locale: en
## Name of the nilavu server
##
## Default: console.megam.io
##
## Acceptable values:
##   - text
  nilavu: console.megam.io
## database backend is a host that the nilavu will connect to
## for getting information about an account (:will be removed in 1.x)
##
## Acceptable values:
##   - text, e.g. localhost, console.megam.io. ipaddress
  riak: 103.56.92.28
## The gateway - API server nilavu connects to.
## Acceptable values:
##    - text, e.g. localhost, api.megam.io, ipaddress
  http_api: 103.56.92.41
## http_logs is a host that the nilavu will connect to for real time log streaming
##
## Acceptable values:
##   - text, e.g. localhost, api.megam.io
  http_logs: localhost:7777/logs
## private.gitlab is a boolean flag that indicates if gitlab is configured or not.
## Default: off
  private_gitlab: off
# http_gitlabs is a host that the nilavu will connect to for pulling data from gitlab  repositories
##
## Acceptable values: http://url
#   - text, e.g. http://localhost, http:/api.megam.io
  http_gitlab: http://gitlab.megam.io/api/v3
# Enable billing, turn it off for testing.
## Acceptable values:
##   - text, e.g. on or off
  billings: off
## Backup ceph storage, host, adminuser, admin password.
  backup:
    enable: off
    host: 192.168.1.102
    username: megdc
    password: randompw
# notification section notifies the handlers based on_trigger conditions.
## 1. on_error: When an error occurs then notify dev support via an email to support@megam.io and hipchat. A notification
## via email happens if the configuration for [email:] exists.
## 2. on_some_hap: Turn notification on for notifying when some happenings needs to be notified. (welcome, reset password, balance topup, low credits)
## Default:
##
## Acceptable values:
##   - text
  notification:
    on_errors: on
    on_some_hap: on
    email:
      id: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
      hipchat:
        api_key: <%= ENV["NIL_HIP_APIKEY"] %>
        room: "Megam"

## Specifies the oauth id/key for various social identities
##
## Default:
##
## Acceptable values:
##   - one of: facebook, github, google
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
