# /var/lib/megam/nilavu.yml
defaults: &defaults
# Enable billing, turn it off for testing.
  billings: off
## Backup ceph storage, host, adminuser, admin password.
  backup:
    enable: off
    host: localhost
    username: megdc
    password: randompw
## locale: default is english
  locale: en
## Name of the nilavu server, welcome email uses this url
  nilavu: https://console.megam.io
## A database backend for nilavu
  riak: localhost
## An api server for nilavu
  http_api: localhost
## http_logs is a host that the nilavu will connect to for real time log streaming
  http_logs: localhost:7777/logs
## private.gitlab is a boolean flag that indicates if gitlab is configured or not.
  private_gitlab: off
# http_gitlabs is a host that the nilavu will connect to for pulling data from gitlab  repositories
  http_gitlab: http://localhost/api/v3
# notification section notifies the handlers based on_trigger conditions.
  notification:
    on_errors: on
    on_some_hap: on
    email:
      id: support@megam.io
      password: <%= ENV["NIL_EMAIL_PASSWORD"] %>
      hipchat:
        api_key: <%= ENV["NIL_HIP_APIKEY"] %>
        room: "Megam"

## Specifies the oauth id/key for various social identities
  oauth:
    facebook:
      client_id: <%= ENV["NIL_FB_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_FB_SECRET_KEY"] %>
    github:
      client_id: <%= ENV["NIL_GIT_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GIT_SECRET_KEY"] %>
    google:
      client_id: <%= ENV["NIL_GOO_CLIENT_ID"] %>
      secret_key: <%= ENV["NIL_GOO_SECRET_KEY"] %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
