monitor:
  metric_source: ganglia
  host: ganglia_host
  base_url: http://monitor.megam.co.in/ganglia
  cluster: megampaas

storage:
  type: riak #s3
  server_url: localhost
  #server_url: https://s3-ap-southeast-1.amazonaws.com
  cloud_tool_bucket: cloudrecipes
  cloud_keys_bucket: cloudkeys

designer:
  host: localhost
  port: 1880
  
api:
  host: localhost
  scheme: http
  pub_key: megamgateway_pub.crt
  private_key: megamgateway.key

keys:
  gogrid_api_key: 
  gogrid_shared_secret: 

  

#if db and production are start from begining of the line it assumes as two inner hashes 
#{"db"=>nil, "production"=>{"adapter"=>"sqlite3"}}
#db:
#  production:
#        adapter: sqlite3
#        database: db/cocdb
#        pool: 5
#        timeout: 5000
