---
chdir: /home/rajthilak/code/megam/workspace/ruby/nilavu
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: log/thin.log
pid: pids/thin.pid
socket: tmp/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 4
daemonize: true
